SELECT a.NAME AS MISSION_NAME,
a.SPACEAGENCY_ID AS SPACEAGENCY_ID,
b.NAME AS AGENCY_NAME,
d.COUNTRY AS COUNTRY
FROM MISSION a INNER JOIN SPACE_AGENCY b ON a.SPACEAGENCY_ID = b.AGENCY_ID
INNER JOIN LOCATION c ON b.LOCATION_ID=c.LOCATION_ID
INNER JOIN ADDRESS d ON c.ADDRESS_ID = d.ADDRESS_ID
WHERE d.COUNTRY = 'USA';

