SELECT a.SYMBOL as SYMBOL,
a.DESCRIPTION AS NAME,
SUM((b.ABUNDANCE_PERCENTAGE / 100) * c.MASS) AS MASS_ABUNDANCE
FROM ELEMENT a
INNER JOIN ELEMENT_OCURRENCE b
ON a.SYMBOL = b.SYMBOL
INNER JOIN CELESTIALBODY c
ON b.CELESTIALBODY_ID = c.CELESTIALBODY_ID
GROUP BY a.SYMBOL, a.DESCRIPTION
ORDER BY SUM(b.ABUNDANCE_PERCENTAGE) DESC
LIMIT 3;