SELECT
PLANET_ID,
NAME AS PLANET_NAME,
ABS(REVOLUTIONPERIOD) / ABS(ROTATIONPERIOD/24) AS ROTATION_DAYS_PER_REVOLUTION
FROM
PLANET
WHERE ABS(REVOLUTIONPERIOD) / ABS(ROTATIONPERIOD/24) <= ALL(SELECT ABS(REVOLUTIONPERIOD) / ABS(ROTATIONPERIOD/24) FROM PLANET);